# Business Case:-

#### Based on given features we need to find whether an employee will leave the company or not.

In [1]:
## Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
## Loading the data
data=pd.read_csv('HR-Employee-Attrition.csv')

## Basic Checks

In [ ]:
data.head(2)#first five rows

In [ ]:
## Getting all columns form the dataset
data.columns

In [ ]:
data.info()

In [ ]:
data.describe()##used to view some basic statistical details like percentile, mean, std etc.

In [ ]:
# we do not have any null values
# we have 2 constant features Employee count and standardhours

In [ ]:
data.describe(include=['O'])#It will give you info about categorical data/columns

In [ ]:
# No null values
# Over18 is constant feature.

## Exploratory Data Analysis

In [ ]:
# Task:- Perform Univariate and Bivariate analysis and get the insights from the data.

### continuous variables

In [5]:
data3=data[['Age',
 'DailyRate',
 'DistanceFromHome',
 'EmployeeNumber',
 'HourlyRate',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']]#continuous variables/columns

# Data Preprocessing

### <font color='red'> Handling missing values </font>

In [ ]:
data.isnull().sum()#null value checking
# no null values


### <font color='red'> Handling Categorical features </font>

In [ ]:
## Categorical data conversion
data1.head(2)

###  1.Attrition

In [ ]:
data.Attrition.unique()#checking unique value in Attrition column

In [7]:
## Manual encoding Attrition feature
data.Attrition=data.Attrition.map({'Yes':1,'No':0})
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

###  2.BusinessTravel

In [ ]:
data.BusinessTravel.unique()#checking unique value

In [9]:
## Encoding BusinessTravel, this feature told the worker who travelled frequenlty has quited the job so let do the
##manual encoding
data.BusinessTravel=data.BusinessTravel.map({'Travel_Frequently':2,'Travel_Rarely':1,'Non-Travel':0})

In [ ]:
data.head()#checking whether imputation properly done or not

### 3.Department

In [ ]:
data.Department.unique()#unique values

In [11]:
data.Department=data.Department.map({'Research & Development':2,'Sales':1,'Human Resources':0})#imputation using map function

In [ ]:
data.head(1)

### 4.EducationField

In [ ]:
 data.EducationField.unique()#unique labels

In [13]:
#using map function
data.EducationField=data.EducationField.map({'Life Sciences':5,'Medical':4,'Marketing':3,'Technical Degree':2,'Other':1,'Human Resources':0 })

In [ ]:
data.head()#checking for imputation

### 5.Gender

In [15]:
data = pd.get_dummies(data, columns=['Gender'], drop_first=True)
data['Gender_Male'] = data['Gender_Male'].astype(int)

df1 = pd.get_dummies(data['Gender'],dtype = 'int',prefix='Gender',drop_first=True)
data = pd.concat([data,df1],axis=1).drop('Gender',axis=1)

In [17]:
data.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Gender_Male
0,41,1,1,1102,1,1,2,5,1,1,...,80,0,8,0,1,6,4,0,5,0

### JobRole

In [ ]:
data.JobRole.value_counts()#checking count for each label

In [19]:
## Encoding JobRole
data.JobRole=data.JobRole.map({'Laboratory Technician':8,'Sales Executive':7,'Research Scientist':6,'Sales Representative':5,
                              'Human Resources':4,'Manufacturing Director':3,'Healthcare Representative':2,'Manager':1,'Research Director':0 })

In [ ]:
data #data.JobRole #checking whether imputation done or not

### Encoding MaritalStatus using label encoding

In [ ]:
data.MaritalStatus.unique()

In [21]:
## Encoding MaritalStatus

from sklearn.preprocessing import LabelEncoder#importing label encoder from sklearn

label = LabelEncoder()#object creation
data.MaritalStatus=label.fit_transform(data.MaritalStatus)#applying label encoder to  marital status

### OverTime

In [ ]:
data.OverTime.value_counts()

In [23]:
## Encoding OverTime
data.OverTime=label.fit_transform(data.OverTime)    #label encoding

In [ ]:
data.head(1)#checking for imputation

In [ ]:
# Since we are using DT and DT is robust to outliers and doesnot require scaling.
# Only conversion of categorical data and missing values should be handled.

## Feature Selection

In [ ]:
## Checking correlation

plt.figure(figsize=(30, 30))#canvas size
sns.heatmap(data3.corr(), annot=True, cmap="RdYlGn", annot_kws={"size":15})#plotting heat map to check correlation

In [25]:
## Removing constant features
data.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours', 'YearsAtCompany', 'TotalWorkingYears'], axis="columns", inplace=True)#droping those columns which have std=0

In [ ]:
data.head()

## Model Creation

In [27]:
## Creating independent and dependent variable
X = data.drop('Attrition', axis=1)#independent variable
y = data.Attrition#dependent variable

In [29]:
## preparing training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
# Balance only the training data

In [31]:
y_train.value_counts()

Attrition
0    913
1    189
Name: count, dtype: int64

In [31]:
## Balacing the data
from collections import Counter# importing counter to check count of each label
from imblearn.over_sampling import SMOTE #for balancing the data
sm=SMOTE()#object creation
print(Counter(y_train))# checking count for each class
X_sm,y_sm=sm.fit_resample(X_train,y_train) #applying sampling on target variable
print(Counter(y_sm)) # checking count after sampling for  each class

Counter({0: 913, 1: 189})
Counter({0: 913, 1: 913})


### <font color='red'> Decision Tree </font>

In [33]:
from sklearn.tree import DecisionTreeClassifier #importing decision tree from sklearn.tree
dt=DecisionTreeClassifier()  #object creation for decision tree
dt.fit(X_sm,y_sm)  #training the model
y_hat=dt.predict(X_test)  #prediction
y_hat   #predicted values

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [35]:
y_train_predict=dt.predict(X_sm)#predicting training data to check training performance
#y_train_predict

In [37]:
## Evalauting the model
from sklearn.metrics import accuracy_score,classification_report,f1_score#importing mertics to check model performance
##Training score

acc_train=accuracy_score(y_sm,y_train_predict)#checking accuracy
acc_train
# overfit model

1.0

In [41]:
print(classification_report(y_sm,y_train_predict))# it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       913
           1       1.00      1.00      1.00       913

    accuracy                           1.00      1826
   macro avg       1.00      1.00      1.00      1826
weighted avg       1.00      1.00      1.00      1826

In [39]:
## test acc
test_acc=accuracy_score(y_test,y_hat)#testing accuracy
test_acc

0.7635869565217391

In [41]:
## test score
test_f1=f1_score(y_test,y_hat)#f1 score
test_f1

0.2564102564102564

In [47]:
print(classification_report(y_test,y_hat))# for  testing

              precision    recall  f1-score   support

           0       0.91      0.81      0.86       320
           1       0.27      0.46      0.34        48

    accuracy                           0.77       368
   macro avg       0.59      0.64      0.60       368
weighted avg       0.83      0.77      0.79       368

In [43]:
pd.crosstab(y_test,y_hat)# confusion matrix for

col_0        0   1
Attrition
0          266  54
1           33  15

### Cross validation

In [ ]:
## K-Fold CV

In [51]:
from sklearn.model_selection import cross_val_score
scores_after = cross_val_score(dt,X,y,cv=3,scoring='f1')
print(scores_after)

print("Cross validation Score:",scores_after.mean())
print("Std :",scores_after.std())
#std of < 0.05 is good.

[0.31724138 0.42682927 0.25352113]
Cross validation Score: 0.3325305914545304
Std : 0.07157396168217288

In [ ]:
## Stratified K-Fold CV

In [73]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)
scores_after = cross_val_score(dt,X,y,cv=skf,scoring='f1')
print(scores_after)

print("Cross validation Score:",scores_after.mean())
print("Std :",scores_after.std())

[0.30434783 0.40909091 0.38297872 0.38461538 0.40909091]
Cross validation Score: 0.3780247504576829
Std : 0.038539537920777724

## Hyperparameters of DecisionTree
* Hyperparameter tuning is searching the hyperparameter space for a set of values that will optimize your model architecture.

* Criterion: The function to measure the quality of a split. Supported criteria are "gini" for the Gini impurity and "entropy" for the information gain.


* Splitter: This is how the decision tree searches the features for a split. The default value is set to “best”. That is, for each node, the algorithm considers all the features and chooses the best split. If you decide to set the splitter parameter to “random,” then a random subset of features will be considered.



* max_depth: This determines the maximum depth of the tree.  we use a depth of two to make our decision tree. ... This will often result in over-fitted decision trees. The depth parameter is one of the ways in which we can regularize the tree, or limit the way it grows to prevent over-fitting..The tree perfectly fits the training data and fails to generalize on testing data.



* min_samples_split:Ideal range is 1 to 40.min_samples_split specifies the minimum number of samples required to split an internal node, while min_samples_leaf specifies the minimum number of samples required to be at a leaf node.



* min_samples_leaf: The minimum number of samples required to be at a leaf node.Similarr to min sample split ,this describes the minimum number of samples at the leaf,the base of tree.Ideal range is 1 to 20.(thershold value to make a decision)like 40

In [ ]:
https://towardsdatascience.com/how-to-tune-a-decision-tree-f03721801680

In [57]:
from sklearn.model_selection import GridSearchCV
#It helps to loop through predefined hyperparameters and fit your estimator (model) on your training set.
#So,in the end, you can select the best parameters from the listed hyperparameters.

In [59]:

#creating dictionary--> key value pair of hyperparameters having key as parameter and values as its values
params = {
    "criterion":("gini", "entropy"), #quality of split
    "splitter":("best", "random"), # searches the features for a split
    # best: searches all features to find the split that gives the best quality. this can be slower on large datasets
    # random: selects a random subset of features and picks the best split among those
    "max_depth":(list(range(1, 20))), #depth of tree range from 1 to 19    # tree pruning parameter for preventing overfitting
    "min_samples_split":[2, 3, 4],    #the minimum number of samples required to split internal node
    "min_samples_leaf":list(range(1, 20)),#minimum number of samples required to be at a leaf node,we are passing list which is range from 1 to 19
}


tree_clf = DecisionTreeClassifier(random_state=3)#object creation for decision tree with random state 3
tree_cv = GridSearchCV(tree_clf, params, scoring="f1", n_jobs=-1, verbose=1, cv=3)
#passing model to gridsearchCV ,
#tree_clf-->model
#params---->hyperparametes(dictionary we created)
#scoring--->performance matrix to check performance
#n_jobs---->Number of jobs to run in parallel,-1 means using all processors.
#verbose=Controls the verbosity: the higher, the more messages.
#>1 : the computation time for each fold and parameter candidate is displayed;
#>2 : the score is also displayed;
#>3 : the fold and candidate parameter indexes are also displayed together with the starting time of the computation.
#cv------> number of flods




tree_cv.fit(X_train,y_train)#training data on gridsearch cv
best_params = tree_cv.best_params_#it will give you best parameters
print(f"Best paramters: {best_params})")#printing  best parameters

Fitting 3 folds for each of 4332 candidates, totalling 12996 fits
Best paramters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_leaf': 10, 'min_samples_split': 2, 'splitter': 'random'})

In [ ]:
tree_cv.best_score_#getting best score form cv

In [61]:
# create a new model with the optimal values
dt1=DecisionTreeClassifier(criterion='gini',max_depth=8,min_samples_leaf= 10,min_samples_split=2,splitter='random')#passing best parameter to decision tree

In [63]:
dt1.fit(X_sm,y_sm)#traing model with best parameter

DecisionTreeClassifier(max_depth=8, min_samples_leaf=10, splitter='random')

In [65]:
y_hat1=dt1.predict(X_test)#predicting
#y_hat1

In [67]:
acc_test=accuracy_score(y_test,y_hat1)#checking accuracy
acc_test

0.7418478260869565

In [69]:
test_f1=f1_score(y_test,y_hat1)#f1_score
test_f1

0.26356589147286824

In [71]:
print(classification_report(y_test,y_hat1))#it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       0.89      0.80      0.84       320
           1       0.21      0.35      0.26        48

    accuracy                           0.74       368
   macro avg       0.55      0.58      0.55       368
weighted avg       0.80      0.74      0.77       368

In [75]:
# Training score
y_pre_hat1=dt1.predict(X_sm)

print("Accuracy_score: ",accuracy_score(y_sm,y_pre_hat1))

print("F1_score: ", f1_score(y_sm,y_pre_hat1))

Accuracy_score:  0.8504928806133626
F1_score:  0.8497523390203633


### <font color='red'> Random Forest  </font>

In [77]:
from sklearn.ensemble import RandomForestClassifier#importing randomforest

rf_clf = RandomForestClassifier(n_estimators=100)#object creation ,taking 100 decision tree in random forest
rf_clf.fit(X_sm,y_sm)#training the data

RandomForestClassifier()

In [78]:
y_predict=rf_clf.predict(X_test)#testing

In [81]:
y_pred1=rf_clf.predict(X_sm) # training

In [83]:
# Testing score:
from sklearn.metrics import accuracy_score,classification_report,f1_score
print("Accuracy: ", accuracy_score(y_test,y_predict))
print("F1_score: ", f1_score(y_test,y_predict))

Accuracy:  0.842391304347826
F1_score:  0.32558139534883723

In [85]:
# Training score:

print("Accuracy: ", accuracy_score(y_sm,y_pred1))
print("F1_score: ", f1_score(y_sm,y_pred1))

Accuracy:  1.0
F1_score:  1.0

## Hyperparameter Tuning

* n_estimators = number of trees in the foreset

* max_features =These are the maximum number of features Random Forest is allowed to try in individual tree. There are multiple options available in Python to assign maximum features

* max_depth =The depth of each tree in the forest. The deeper the tree, the more splits it has and it captures more information              about the data

* min_samples_split =the minimum number of samples required to split an internal node. This can vary between considering at least one sample at each node to considering all of the samples at each node

* min_samples_leaf = minimum number of data points allowed in a leaf node
* bootstrap = method for sampling data points (with or without replacement)

In [87]:
#Random Search sets up a grid of hyperparameter values and selects random combinations to train the model and score.
#This allows you to explicitly control the number of parameter combinations that are attempted.
#The number of search iterations is set based on time or resources.
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=10)]#List Comprehension-using for loop in list
max_features = ['auto', 'sqrt']#maximum number of features allowed to try in individual tree
max_depth = [int(x) for x in np.linspace(10, 110, num=11)]#List Comprehension-using for loop in list
max_depth.append(None) # finally add None. Max_depth=None gives you fully grown trees.
min_samples_split = [2, 5, 10]#minimum number of samples required to split an internal node
min_samples_leaf = [1, 2, 4]#minimum number of samples required to be at a leaf node.


#dictionary for hyperparameters
random_grid = {'n_estimators': n_estimators, 'max_features': max_features,
               'max_depth': max_depth, 'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf_clf1 = RandomForestClassifier(random_state=42)#model

rf_cv = RandomizedSearchCV(estimator=rf_clf1, scoring='f1',param_distributions=random_grid, n_iter=100, cv=3,
                               verbose=1, random_state=42, n_jobs=-1)
#estimator--number of decision tree
#scoring--->performance matrix to check performance
#param_distribution-->hyperparametes(dictionary we created)
#n_iter--->Number of parameter settings that are sampled. n_iter trades off runtime vs quality of the solution.default=10
##cv------> number of flods
#verbose=Controls the verbosity: the higher, the more messages.
#n_jobs---->Number of jobs to run in parallel,-1 means using all processors.

rf_cv.fit(X_train, y_train)##training data on randomsearch cv
rf_best_params = rf_cv.best_params_##it will give you best parameters
print(f"Best paramters: {rf_best_params})")##printing  best parameters

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Best paramters: {'n_estimators': 600, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 60, 'bootstrap': False})

In [89]:
#rf_clf2 = RandomForestClassifier(rf_best_params)#passing best parameter to randomforest
rf_clf2 = RandomForestClassifier(n_estimators= 600, min_samples_split= 5, min_samples_leaf= 1, 
                                 max_features= 'sqrt', max_depth= 60)
rf_clf2.fit(X_sm, y_sm)#training

y_predict=rf_clf2.predict(X_test)#testing
print("F1_score: ", f1_score(y_test,y_predict)) #checking performance

F1_score:  0.3333333333333333

In [91]:
# training score:

y_pre1=rf_clf2.predict(X_sm)
print("F1_score: ", f1_score(y_sm,y_pre1))

F1_score:  1.0

### <font color='red'> Bagging </font>

In [93]:
from sklearn.neighbors import KNeighborsClassifier#USING KNN
KNN1=KNeighborsClassifier() ## model object creation
KNN1.fit(X_sm,y_sm)  ## fitting the model
y_hat_knn=KNN1.predict(X_test) ## getting the predict from created model

In [95]:
accuracy_score(y_test,y_hat_knn)

0.6358695652173914

In [97]:
f1_score(y_test,y_hat_knn)

0.1927710843373494

In [99]:
from sklearn.ensemble import BaggingClassifier #import bagging 

## model object creation
model_bagg1=BaggingClassifier(estimator=KNN1,n_estimators=500, max_samples=0.5, max_features=0.75) 

# base_estimator---> algorithm which you want to pass
# n_estimators-----> number of base learners


## fitting the model
model_bagg1.fit(X_sm,y_sm) 

## getting the prediction
y_hat_bagg=model_bagg1.predict(X_test) 

# testing score:
f1_score(y_test,y_hat_bagg)

0.20359281437125748

In [100]:
#Training score:
y_pr = model_bagg1.predict(X_sm)    
f1_score(y_sm,y_pr)

0.8584382871536524

# Boosting


### <font color='red'> Gradient Boosting </font>

In [103]:
## importing the model library
from sklearn.ensemble import GradientBoostingClassifier
gbm=GradientBoostingClassifier() ## object creation
gbm.fit(X_sm,y_sm) ## fitting the data
y_gbm=gbm.predict(X_test)#predicting the price

#testing score:
#from sklearn.metrics import f1_score
f1_score(y_test,y_gbm)

0.4742268041237113

In [104]:
# training score:
y_pre_g=gbm.predict(X_sm)
f1_score(y_sm,y_pre_g)

0.9499725123694338


### <font color='red'> XGBoost </font>

!pip install xgboost

In [107]:

## model creation
#importing the model library
from xgboost import XGBClassifier

xgb_r= XGBClassifier() ## object creation
xgb_r.fit(X_train, y_train)# fitting the data
y_hat=xgb_r.predict(X_test)#predicting the price

# testing score:
f1_score(y_test,y_hat)

0.3888888888888889

In [109]:
# training score:
y_h=xgb_r.predict(X_train)
f1_score(y_train,y_h)

1.0

'n_estimators' - No. of decision trees
'learning_rate': 
'max_depth':  tree pruning parameter - to control the growth of the tree
'min_child_weight':  how the decision tree inside XGBoost decides whether or not to split a node into further branches (called partitioning).
Each time the algorithm splits a node:
             It partitions the data into two groups.
             This split should ideally reduce the loss (i.e., improve predictive performance).
'gamma':  regularization parameter to control whether a split should happen
          Minimum loss reduction required to make a further partition on a leaf node

In [118]:
from sklearn.model_selection import GridSearchCV
# Define hyperparameters grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 4, 5], # tree pruning
    'min_child_weight': [5,6,7,8], # 
    'gamma': [0, 0.1, 0.2],
}

# Create XGBoost classifier
xgb_model = XGBClassifier()

# Instantiate GridSearchCV
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='f1', verbose=1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Print the best parameters found
print("Best parameters:", grid_search.best_params_)

Fitting 3 folds for each of 324 candidates, totalling 972 fits
Best parameters: {'gamma': 0.1, 'learning_rate': 0.05, 'max_depth': 3, 'min_child_weight': 8, 'n_estimators': 300}

In [113]:
xg = XGBClassifier(gamma= 0.1, learning_rate= 0.1, max_depth=5, min_child_weight=5, n_estimators=300)
xg.fit(X_sm, y_sm)
y_hat4 = xg.predict(X_test)

#testing score:
f1_score(y_test, y_hat4)

0.3870967741935484

In [115]:
# training score:

y_pre_x = xg.predict(X_sm)

f1_score(y_sm, y_pre_x)

1.0